### ISSUE TITLE
Develop a New React Routing Page

### ISSUE THREAD

**Issue by Kvngxel** [Kvngxel/locale#17]
# Description:

This aims to add a new routing page to our React application, improving user navigation and providing a dedicated space for specific content or features. It involves tasks such as setting up routing, creating a React component, defining routes, designing the user interface, implementing functionality, testing, integration, adding navigation elements, error handling, and documentation. 

# Objective:

The objective of this GitHub issue is to develop a new page with routing functionality in our React application. This addition will enhance user navigation and provide a dedicated space for specific content or features. 

# Acceptance Criteria:

- [x] Routing Setup: Routing functionality within the React application is established, or if it already exists, it is confirmed to be functioning correctly.

- [x] React Component Creation: A new React component dedicated to the content and functionality of the new page is successfully created.

- [x] Route Definition: The route for the new page is defined in the application's routing configuration, ensuring that it follows a clear and logical structure.

- [x] Functionality Implementation: Any necessary functionality, data fetching, or interactions required for the new page are successfully implemented, ensuring that the page operates as intended.

- [x] Integration Testing: The new page is verified to integrate seamlessly with the existing application and navigation. Users can navigate to and from the new page without encountering issues.

- [x] Error Handling: Proper error handling and fallback mechanisms are implemented on the new page, ensuring a user-friendly experience in the event of errors or missing data.

- [x] Documentation: Documentation is created, detailing the functionality and usage of the new page. This documentation serves as a reference for future development and maintenance.

**Comment by AliyuAliyu1** [comment]
Completed the Routing
