### ISSUE TITLE
Create Backend Endpoints for Directory Routes and Set Up Redux on Frontend

### ISSUE THREAD

**Issue by Kvngxel** [Kvngxel/locale#31]
# Description:

This GitHub issue focuses on two major tasks: creating backend endpoints for directory routes and setting up Redux on the frontend. The goal is to establish a structured and functional backend with necessary endpoints and implement Redux to manage the application's state efficiently on the frontend.

# Acceptance Criteria:

Backend - Create Endpoints for Directory Routes:

Endpoint Creation:

- [ ] Create endpoints for various directory routes, including routes for users, files, folders, etc.
 Ensure these endpoints follow a RESTful API design and adhere to best practices.
Functionality:

- [ ] Implement necessary functionality for each endpoint to handle CRUD operations (Create, Read, Update, Delete).
Ensure the endpoints interact correctly with the database and return appropriate responses.
Error Handling:

- [ ]  Implement proper error handling mechanisms for each endpoint to provide meaningful error responses in case of failures.

- [ ]  Document the newly created endpoints, including their functionality and usage.
 Provide usage examples and request/response formats for each endpoint.
Frontend - Set Up Redux:

Redux Setup:

- [ ]  Install necessary dependencies for Redux, including redux, react-redux, and redux-thunk.
 Set up the Redux store, reducers, and actions.
Integration:

- [ ]  Integrate Redux into the frontend application to manage the state effectively.
 Connect relevant components to the Redux store and utilize the state where needed.
Action Creators:

- [ ]  Create action creators for various functionalities to handle state changes.
Documentation:

- [ ]  Document the process of setting up Redux, explaining the structure, and demonstrating how to use Redux in the project.

**Comment by o-david** [comment]
Back end has Been set up
